package practice;

public class exception1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int a = 10;
		int b = 0 ;
		
		try {
			int c1 = a/b;
		}
		catch (Exception e) {
			System.out.println("error occured");
		}
		char[] c1 = null;
		System.out.println(c1);
		System.out.println("end");
		
	}

}
